### ISSUE TITLE
Build fails on Linux on hawtjni-plugin step

### ISSUE THREAD

**Issue by m91snik** [p8a/yara-java#10]
Hi,

I've tried to build yara-java on OpenSuse Leap and I followed instructions to clone and make Yara first of all and after that clone yara-java to corresponding directory and run `mvn clean install` there.

I noticed that `hawtjni-plugin` plugin was configured only for `mac`, so I've added `unix` profile as 

```
<id>unix</id>
<activation><os><family>unix</family></os></activation>
<build>
    <plugins>
        <plugin>
            <groupId>org.fusesource.hawtjni</groupId>
            <artifactId>maven-hawtjni-plugin</artifactId>
            <configuration>
                <osgiPlatforms>
                    <osgiPlatform>osname=Linux;processor=x86-64</osgiPlatform>
                </osgiPlatforms>
                <configureArgs>
                    <arg>--with-universal=x86_64</arg>
                    <arg>--disable-shared</arg>
                </configureArgs>
                <platform>linux64</platform>
            </configuration>
        </plugin>
    </plugins>
</build>
```

without `--disable-shared` arg I'm getting error

```
[INFO] *** static library /opt/workspace/samples/yara/yara-java/target/native-build/../../../libyara/.libs/libyara.a is not portable!
[INFO] libtool: link: gcc -shared  -fPIC -DPIC  src/.libs/yara-wrapper_stats.o src/.libs/yara-wrapper.o src/.libs/yara-wrapper_structs.o src/.libs/hawtjni.o src/.libs/hawtjni-callback.o   /opt/workspace/samples/yara/yara-java/target/native-build/../../../libyara/.libs/libyara.a  -O2   -Wl,-soname -Wl,libyara-wrapper-3.4.0-SNAPSHOT.so -o .libs/libyara-wrapper-3.4.0-SNAPSHOT.so
[INFO] /usr/lib64/gcc/x86_64-suse-linux/4.8/../../../../x86_64-suse-linux/bin/ld: /opt/workspace/samples/yara/yara-java/target/native-build/../../../libyara/.libs/libyara.a(compiler.o): relocation R_X86_64_32 against `yr_object_destroy' can not be used when making a shared object; recompile with -fPIC
[INFO] /opt/workspace/samples/yara/yara-java/target/native-build/../../../libyara/.libs/libyara.a: error adding symbols: Bad value
```
and with `--disable-shared` as in config above, I'm getting
```
Make based build did not generate: /opt/workspace/samples/yara/yara-java/target/native-build/target/lib/libyara-wrapper.so
```
but in the same time I see in lib64 directory that wrapper library is generated as .a:
```
yara-java/target/native-build/target/lib64> ls
libyara-wrapper.a  libyara-wrapper.la
```

@p8a, have you checked yara-java on non-mac platforms? May be you have advices about solving this issue

**Comment by p8a** [comment]
I'm actively using it on Linux (CentOS and Ubuntu). I'll take a look to see what's going on.

**Comment by p8a** [comment]
I successfully compiled on OpenSuse Leap without any modifications to yara-java, what you need to do is build yara with -fPIC:

```
./bootstrap
CFLAGS=-fPIC ./configure
make 
```

Let me know if this is still an issue.

**Comment by m91snik** [comment]
thanks @p8a , I got the same result using `CFLAGS=-fPIC ./configure` as I had with `--disable-shared`.
.so file is generated and put into `lib64` directory, but hawtjni tries to use it from `lib`.

I've opened an issue for them https://github.com/fusesource/hawtjni/issues/28

**Comment by p8a** [comment]
I'm going to close it since it seems unrelated to yara-java, please reopen otherwise.

**Comment by m91snik** [comment]
@p8a I cannot reopen issue, because you closed it, i.e. by github rules "you cannot re-open your own issues if a repo collaborator closed them".

So, pls open it because I believe that if yara-java project cannot be used on linux 64x (because of hawtjni maven plugin) then it should be described somewhere or plugin should be replaced, assuming that it has bug. or another fix should be provided.

You've mentioned that you are able to build yara-java on linux, even on OpenSuse.
Did you do it on x86 or 64x?

**Comment by m91snik** [comment]
@p8a , I've solved it by using solved it by using --libdir=${project.build.directory}/native-build/target/lib arg for linux amd64. I will open PR with changes for linux amd64 platform

**Comment by p8a** [comment]
That is incorrect, it looks like for some reason you are compiling the 32 bit version. What is the target architecture of the so that gets generated ? Can you attach your build log (both for yara and yara-java) ?

I am actively using yara-java on Linux (CentOS, Ubuntu) 64 bit and I had no problems building in the same env as you - 64 bit as well.

**Comment by m91snik** [comment]
@p8a , I build it for 64 bit system. It seems to be wrong that https://github.com/fusesource/hawtjni/blob/master/maven-hawtjni-plugin/src/main/java/org/fusesource/hawtjni/maven/BuildMojo.java calls ./configure script without specifying libdir explicitly, but later assumes that libdir was "lib" and not "lib64".

So, point is that .so is generated correctly and placed to lib64, but [BuildMojo tries to use it from "lib" directory](https://github.com/fusesource/hawtjni/blob/master/maven-hawtjni-plugin/src/main/java/org/fusesource/hawtjni/maven/BuildMojo.java#L343).

So, specifying libdir explicitly solves this issue and it's quite quick fix.
I think that it's a kind of workaround because more general solution will be BuildMojo fix to use not hardcoded "lib", but evaluate it based on architecture.
