### ISSUE TITLE
Question regarding thread safety

### ISSUE THREAD

**Issue by shollander** [p8a/yara-java#14]
I would like to use yara-java in a multithreaded environment. Which classes can be reused across multiple threads and which cannot? I am using the same rules for all files that I scan. In a simple performance test I get close to a 50% performance increase when reusing the `YaraScanner` object. I just don't know if it is safe to do so.

**Comment by shollander** [comment]
I just submitted a pull request #15 for enabling multithreaded reuse

**Comment by p8a** [comment]
Merged pull request, thanks!
