### ISSUE TITLE
Buffer over-read possible with yara_match_value()

### ISSUE THREAD

**Issue by shollander** [p8a/yara-java#16]
1894dd7f335d67336b5b19b59ac27fdecd6b4877 modified yara_match_value to account for changes in Yara 3.5.0. It appears that this was not done correctly and can result in over-reading the `YARA_MATCH->data` buffer. According to the [Yara documentation](http://yara.readthedocs.io/en/v3.5.0/capi.html#c.YR_MATCH) `data_length` should be used as the actual length of `data`. `match_length` is the true length of the match, but not necessarily the length of the `data` buffer.

**Comment by shollander** [comment]
Added pull request #17

**Comment by p8a** [comment]
Merged pull request.
