### ISSUE TITLE
error: 'YR_MATCH' has no member named 'match_length'

### ISSUE THREAD

**Issue by m91snik** [p8a/yara-java#18]
When I build yara-java on Linux64 I get
``
[INFO] executing: /bin/sh -c make install
[INFO] /bin/sh ./libtool  --tag=CC   --mode=compile gcc -DHAVE_CONFIG_H -I. -I./src     -g -O2 -I/home/m91snik/workspace/samples/yara/yara-java/target/native-build/../../../libyara/include -I/opt/env/jdk1.8.0_65/include -I/opt/env/jdk1.8.0_65/include/linux -c -o src/yara-wrapper.lo src/yara-wrapper.c
[INFO] libtool: compile:  gcc -DHAVE_CONFIG_H -I. -I./src -g -O2 -I/home/m91snik/workspace/samples/yara/yara-java/target/native-build/../../../libyara/include -I/opt/env/jdk1.8.0_65/include -I/opt/env/jdk1.8.0_65/include/linux -c src/yara-wrapper.c  -fPIC -DPIC -o src/.libs/yara-wrapper.o
[INFO] In file included from src/yara-wrapper.c:2:0:
[INFO] src/yara-wrapper.h: In function 'yara_match_value':
[INFO] src/yara-wrapper.h:145:36: error: 'YR_MATCH' has no member named 'match_length'
[INFO]      if (0 != (buffer = malloc(match->match_length + 1))) {
[INFO]                                     ^
[INFO] src/yara-wrapper.h:146:32: error: 'YR_MATCH' has no member named 'match_length'
[INFO]          memset(buffer, 0, match->match_length + 1);
[INFO]                                 ^
[INFO] In file included from /usr/include/string.h:631:0,
[INFO]                  from /home/m91snik/workspace/samples/yara/yara-java/target/native-build/../../../libyara/include/yara/modules.h:22,
[INFO]                  from /home/m91snik/workspace/samples/yara/yara-java/target/native-build/../../../libyara/include/yara.h:23,
[INFO]                  from src/yara-wrapper.h:4,
[INFO]                  from src/yara-wrapper.c:2:
[INFO] src/yara-wrapper.h:147:57: error: 'YR_MATCH' has no member named 'match_length'
[INFO]          strncpy(buffer, (const char* )match->data, match->match_length);
``

@p8a , please note that I was able to build yara-java on Linux64 after this fix https://github.com/p8a/yara-java/pull/11, but now it's not possible again.

**Comment by p8a** [comment]
Master builds now on top of yara 3.5.0, please make sure you have the latest yara code.

This is commit https://github.com/p8a/yara-java/commit/1894dd7f335d67336b5b19b59ac27fdecd6b4877

**Comment by m91snik** [comment]
thanks for fast reply, @p8a . I didn't notice that version of yara was updated to 3.5.0, I will try it today and close issue if it works

**Comment by p8a** [comment]
is this still an issue ? Thanks

**Comment by m91snik** [comment]
This was fixed by using correct 3.5.0 yara as you recommended above
