### ISSUE TITLE
Native build / OS X 10.11.6

### ISSUE THREAD

**Issue by gills** [p8a/yara-java#24]
Configuration:
Macbook Pro Mid-2015 / OS X 10.11.6
openssl 1.0.2 installed separately to /usr/local/opt/openssl

configure [maven-hawtjni-plugin] was blowing up on the separate `<arg>-L/usr/local/opt/openssl/lib</arg>`. I found it builds correctly by combining all the linker arguments into the same `<arg/>`:

`<arg>LDFLAGS=${jni-with-crypto} -L/usr/local/opt/openssl/lib -lcrypto</arg>`

Do you know if anyone else has run into this issue?

**Comment by p8a** [comment]
Not that I know of, personally I'm using OS X 10.12 for development.
